[package]
name = "nix-test"
version = "0.1.0"
authors = ["Stoeffel <schtoeffel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
junit-report = "0.2.0"
clap = "2.33.0"
